namespace GameTranslator.Application.Pipeline;

public sealed class LiveTranslationPipelineUpdate
{
    public LiveTranslationPipelineUpdate(
        TranslationPipelineBatchResult batchResult,
        bool overlayChanged,
        IEnumerable<string>? cancelledZoneIds = null,
        CandidatePipelineReadiness? candidateReadiness = null,
        IEnumerable<LiveCandidateLifecycleEvent>? candidateLifecycleEvents = null,
        int droppedCandidateLifecycleEventCount = 0)
    {
        BatchResult = batchResult ?? throw new ArgumentNullException(nameof(batchResult));
        if (droppedCandidateLifecycleEventCount < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(droppedCandidateLifecycleEventCount));
        }

        OverlayChanged = overlayChanged;
        CancelledZoneIds = (cancelledZoneIds ?? Array.Empty<string>())
            .Distinct(StringComparer.Ordinal)
            .ToArray();
        CandidateReadiness = candidateReadiness ?? CandidatePipelineReadiness.Disabled;
        CandidateLifecycleEvents = (candidateLifecycleEvents ?? Array.Empty<LiveCandidateLifecycleEvent>()).ToArray();
        DroppedCandidateLifecycleEventCount = droppedCandidateLifecycleEventCount;
    }

    public TranslationPipelineBatchResult BatchResult { get; }

    public bool OverlayChanged { get; }

    public IReadOnlyList<string> CancelledZoneIds { get; }

    /// <summary>
    /// Session-only readiness telemetry for the candidate-region policy.
    /// </summary>
    public CandidatePipelineReadiness CandidateReadiness { get; }

    /// <summary>
    /// Bounded candidate/overlay diagnostic events generated by this session update. Consumers that
    /// need a local session trace append these batches and remove the oldest events when
    /// <see cref="DroppedCandidateLifecycleEventCount"/> advances.
    /// </summary>
    public IReadOnlyList<LiveCandidateLifecycleEvent> CandidateLifecycleEvents { get; }

    /// <summary>
    /// Number of oldest lifecycle events discarded from the bounded session trace.
    /// </summary>
    public int DroppedCandidateLifecycleEventCount { get; }
}
