<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GameTranslator.Application\GameTranslator.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InfrastructureCompositionModule Include="..\GameTranslator.Infrastructure\bin\$(Configuration)\net9.0-windows10.0.19041.0\GameTranslator.Infrastructure.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.17" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.17" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <Target Name="BuildInfrastructureCompositionModule" BeforeTargets="Build">
    <MSBuild
      Projects="..\GameTranslator.Infrastructure\GameTranslator.Infrastructure.csproj"
      Targets="Build"
      Properties="Configuration=$(Configuration);RuntimeIdentifier=$(RuntimeIdentifier)" />
  </Target>

  <Target Name="CopyInfrastructureCompositionModule" AfterTargets="Build">
    <ItemGroup>
      <InfrastructureCompositionModuleRuntime Include="..\GameTranslator.Infrastructure\bin\$(Configuration)\net9.0-windows10.0.19041.0\**\*" />
    </ItemGroup>
    <Copy
      SourceFiles="@(InfrastructureCompositionModuleRuntime)"
      DestinationFiles="@(InfrastructureCompositionModuleRuntime->'$(OutDir)%(RecursiveDir)%(Filename)%(Extension)')"
      SkipUnchangedFiles="true"
      Condition="'@(InfrastructureCompositionModuleRuntime)' != ''" />
  </Target>

  <Target Name="PublishInfrastructureCompositionModule" AfterTargets="Publish">
    <ItemGroup>
      <InfrastructureCompositionModulePublish Include="..\GameTranslator.Infrastructure\bin\$(Configuration)\net9.0-windows10.0.19041.0\$(RuntimeIdentifier)\**\*" />
    </ItemGroup>
    <Copy
      SourceFiles="@(InfrastructureCompositionModulePublish)"
      DestinationFiles="@(InfrastructureCompositionModulePublish->'$(PublishDir)%(RecursiveDir)%(Filename)%(Extension)')"
      SkipUnchangedFiles="true"
      Condition="'@(InfrastructureCompositionModulePublish)' != ''" />
  </Target>

</Project>
