<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.17" />
    <PackageReference Include="TesseractOCR" Version="5.5.2" />
    <ProjectReference Include="..\GameTranslator.Application\GameTranslator.Application.csproj" />
    <ProjectReference Include="..\GameTranslator.Domain\GameTranslator.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
